version: '2'
services:
  mysql:
    build: ./build/mysql
    container_name: mysql
    volumes:
      - ./build/mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php:
    build: ./build/php
    container_name: php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    ports:
      - 3000:80
